// Page prose for the rack plan. Strings marked `html` may contain inline markup (<code>, <span class="mono">) and are
// rendered with dangerouslySetInnerHTML; everything else is plain text. Keep facts here in sync with `cables.ts`.

export const LEAD = "Kendall Howard LINIER 42U cabinet (24 in deep, glass doors). Bottom to top: SilverStone RM51 gaming PC, RM44 Sam's PC, RM44 Proxmox server, UCI modem, UDM Pro, USW Pro Max 24 PoE, UniFi 24-slot keystone patch panel, and the Tripp Lite PDUMH20 metered PDU at the very top. Rack-side network, power, display, and USB runs are included. Sam's PC has power, Ethernet, HDMI, and one USB-C hub upstream; the gaming PC has power, Ethernet, DisplayPort, and one USB hub upstream. The remote server has power and Ethernet only.";

export interface RationaleCard { eyebrow: string; title: string; body: string }
export const RATIONALE: RationaleCard[] = [
  { eyebrow: "display and peripherals", title: "Two desk runs per PC; the server stays headless", body: "Sam's graphics card connects to the display over HDMI, with a separate USB-C upstream cable to the hub. The gaming PC uses DisplayPort plus a single USB upstream to its peripheral hub. These runs leave the back of each PC and go directly to the desk, separate from Ethernet and the network patch panel. The remote server needs only its PSU cord and Ethernet cable. Desk markers and exact PC port positions in the viewer are schematic; measure cable lengths and leave service slack before moving either PC." },
  { eyebrow: "verified over ssh · ethtool nic0", title: "Your server has a 5 GbE NIC that is stuck at 1 GbE", body: "The Proxmox host runs a Realtek RTL8126 5GbE controller, but the TP-Link only offers gigabit, so it negotiated 1000 Mb/s. On switch port 17 (a 2.5 GbE PoE++ port) the plan allows a 2.5 GbE link; verify negotiation after cutover. That is the single biggest speed win in the whole rack: Jellyfin direct-play, Mac-to-CT rsync deploys, and PC-to-server file copies can benefit where the other endpoint also supports 2.5 GbE; a gigabit dock remains limited to 1 GbE." },
  { eyebrow: "switch fabric", title: "PC to server traffic never touches the router", body: "All three machines sit on the same switch and the same VLAN, so the Pro Max forwards between them in hardware at line rate. The UDM Pro only sees traffic leaving for the internet or crossing a VLAN. That is why the PCs go on the switch, not on the eight 1 GbE LAN ports on the UDM Pro, which would cap them at gigabit." },
  { eyebrow: "trunk", title: "10 G DAC between switch and router", body: "The switch to UDM Pro link carries every internet flow, the seedbox WireGuard tunnel, all Cloudflare tunnel traffic, and any future inter-VLAN routing. A copper SFP+ DAC (UACC-DAC-SFP10-0.5M) costs less than a patch cable and provides shared headroom above the access links. Never use a 1 GbE RJ45 port for this trunk." },
  { eyebrow: "wan", title: "Modem into the RJ45 WAN port, not the SFP+", body: "The UCI has a 2.5 GbE Ethernet port, but UDM Pro RJ45 WAN port 9 limits this path to 1 Gb/s shared by the rack. Spectrum download and upload rates are unverified. Remote streaming may be limited by upload well below the wired link rate. A compatible multi-gig RJ45 SFP+ module in WAN port 10 can remove the 1 GbE port limit if the subscribed tier requires it." },
  { eyebrow: "addressing", title: "Keep 192.168.0.0/24 with the gateway at .1", body: "Every static IP, the cloudflared route table, pg_hba allow-lists on CT 107, the Velocity forward, and the seedbox killswitch all assume the current subnet. Set the UDM Pro default network to 192.168.0.1/24 and the whole homelab comes up without touching a single guest. Then add DHCP reservations so CT 107 stops living on a lease at .42." },
  { eyebrow: "wi-fi", title: "The UDM Pro has no radio. You need an AP.", body: "The TP-Link was your Wi-Fi. The UDM Pro is not. Budget a U7 Pro on switch port 20 (2.5 GbE PoE++), run from patch panel port 20. The Pro Max has a 400 W PoE budget, so cameras and more APs later cost nothing in rack space." },
  { eyebrow: "rack order · kendall howard 42u", title: "Your order is already right. Keep it.", body: "Bottom to top: RM51 gaming PC (5U, the heaviest box), the two RM44s, then UCI, UDM Pro, switch, patch panel, and the Tripp Lite PDU in the top unit where its cord reaches the top cable access in inches. Panel directly over the switch means 6 inch patch cords for every house drop, UDM Pro under the switch keeps the DAC at 0.5 m, and the modem sits where coax enters once. Inside the cabinet, everything that lives on the back (the three PC NICs, the UCI's coax, the keystone side of the patch panel) reaches the front through the gap between the rails and the side panel, so no cord ever crosses a chassis face. The PDU's twelve rear outlets sit at the top of the rear cable channel, so every power cord runs straight up the back and never crosses a data cord. One real constraint: the RM51 chassis is approximately 485 mm deep before any rear cage or connectors and the LINIER 24 in cabinet has about 495 mm of usable depth, so set the rear rails all the way back and use slim or 90-degree-boot cords on the PC NICs. The empty U below the RM51 is where a UPS goes." },
  { eyebrow: "patch panel discipline", title: "LAN runs terminate on the panel, with the switch patched 1:1", body: "All 24 panel slots are patched to switch ports 1 to 24 with identical 0.15 m UniFi Etherlighting cords, so slot number equals port number forever. House runs punch down on Cat6A keystones in the back of the panel. The three PCs plug into keystone couplers in the back of slots 17 to 19, so even the in-rack machines show up on the panel and the switch face never gets touched again. UCI to UDM Pro WAN is 0.15 m, the DAC is 0.5 m. The only long cords run from the PC rear NICs up the rear of the cabinet to the panel: server 1 m, Sam 1.5 m, gaming 2 m." }
];

export const PORT_INTRO = "Ports 1 to 8 are 1 GbE PoE+; 9 to 16 are 1 GbE PoE++; 17 to 24 are 2.5 GbE PoE++. Ports 25 and 26 are 10 G SFP+. Every port is patched to the same-numbered panel slot; spares are cabled and simply unlit until a keystone goes in behind them.";
/** Switch port number -> what is patched behind it (1:1 with panel slots). Unlisted ports are cabled spares. */
export const PORT_ASSIGNMENTS: Record<number, string> = { 17: "Server", 18: "Gaming", 19: "Sam", 20: "U7 Pro AP", 9: "TV drop", 10: "Office" };

export interface BomRow { item: string; qty: string; purpose: string }
/** `item` may contain inline HTML. */
export const BOM: BomRow[] = [
  { item: "Existing desk cables: HDMI, DisplayPort, USB-C upstream, USB upstream", qty: "1 each", purpose: "Retain the four existing runs. Sam: HDMI + USB-C hub. Gaming: DisplayPort + USB hub. Measure installed lengths; gaming USB connector type and cable generations are unspecified." },
  { item: "UniFi 10G SFP+ DAC, 0.5 m <span class=\"mono\">(UACC-DAC-SFP10-0.5M)</span>", qty: "1", purpose: "Switch port 26 to UDM Pro port 11. The trunk." },
  { item: "UniFi U7 Pro access point", qty: "1", purpose: "Replaces TP-Link Wi-Fi. Powered by switch port 20 at 2.5 GbE." },
  { item: "UniFi Etherlighting patch cables, 0.15 m <span class=\"mono\">(UACC-Cable-Patch-EL-0.15M-W)</span>", qty: "25", purpose: "All 24 panel slots to switch ports 1 to 24, plus UCI to UDM Pro WAN. The translucent boots light up with the port's Etherlighting color." },
  { item: "UniFi Cat6A keystone couplers", qty: "3", purpose: "Back of panel slots 17 to 19. The PC patch cords plug into these so the in-rack machines terminate on the panel like everything else." },
  { item: "Slim Cat6a patch cords, 1 m / 1.5 m / 2 m", qty: "3", purpose: "Server, Sam's PC, gaming PC rear NICs up the rear of the cabinet to the couplers. Slim boots matter here because of the RM51 depth." },
  { item: "C13 power cords, 0.5 m x3, 1 m, 1.5 m, 2 m", qty: "6", purpose: "Switch, UDM Pro, UCI on short cords to PDU outlets 1 to 3; the three PCs on longer cords to outlets 6, 8, 10." },
  { item: "UniFi keystone jacks <span class=\"mono\">(UACC-Keystone-Cat6A)</span> + punchdown tool + Cat6a solid-core spool", qty: "as needed", purpose: "House runs terminate on keystones snapped into the back of the panel, and in matching wall plates. Same numbers at both ends." },
  { item: "SilverStone rail kits (RMS08 for RM51, RMS05 for RM44) if not already fitted", qty: "3", purpose: "Slide-out access to the rear I/O without unracking. Kendall Howard uses square-hole rails, so use cage nuts." },
  { item: "1U rackmount UPS, 1000 to 1500 VA", qty: "1", purpose: "Cable modems drop on a blink. Keeps Proxmox, UDM, switch and UCI up through short outages." },
  { item: "Optional: multi-gig RJ45 SFP+ module <span class=\"mono\">(UACC-CM-RJ45-MG)</span>", qty: "1", purpose: "Only if Spectrum tier goes above 1 Gbps. Moves WAN to UDM Pro port 10." }
];

export interface Step { title: string; body: string }
/** `body` may contain inline HTML (<code>). */
export const STEPS: Step[] = [
  { title: "Label the four desk runs.", body: "Mark D1 (Sam HDMI), U1 (Sam USB-C hub), D2 (gaming DisplayPort), and U2 (gaming USB hub) at both ends before moving the chassis. Reconnect the display cables to the graphics cards and verify each hub's peripherals afterward. The remote server retains only power and Ethernet." },
  { title: "Cable it cold.", body: "The stack is already racked in the right order. Run every data and power cord per the schedule before powering anything; the PDU meter should read near zero with everything off. The three PC NICs are on the rear I/O shields, so route those cords up the rear of the cabinet into the couplers on the back of the panel, then patch all 24 slots to the switch in order. House runs and the coax enter through the LINIER top cable access and terminate on keystones in the back of the patch panel first." },
  { title: "Adopt the UDM Pro on a laptop first.", body: "Set the default network to 192.168.0.1/24, DHCP pool 192.168.0.200 to .250 so it never collides with the static guests in .24 to .161." },
  { title: "Add DHCP reservations.", body: "CT 107 opendock-db at 192.168.0.42 (it is on a lease today), then any PC you want pinned. Copy the MACs from the TP-Link client list before you unplug it." },
  { title: "Recreate the one port forward.", body: "TCP 25565 to 192.168.0.24 for the Velocity proxy. Do not recreate 25566 or 2212. CT 112 is gone and those forwards are dangling." },
  { title: "Move the coax.", body: "Power down the old modem, connect coax to the UCI, and call Spectrum or use the app to provision the new MAC. Expect 5 to 15 minutes." },
  { title: "Plug the server in last and verify the link.", body: "Run <code>ethtool nic0 | grep Speed</code> on the host. It must say 2500Mb/s. Then confirm cloudflared reconnects with <code>journalctl -u cloudflared -n 20</code>, and that CT 101's <code>curl --interface wg0 api.ipify.org</code> returns the AirVPN exit." },
  { title: "Adopt the AP and retire the TP-Link.", body: "Same SSID and passphrase as before so every phone, the Apple TV running Prime, and the iPhone dev builds reconnect without re-pairing." },
  { title: "Fix the resolver on the host.", body: "The Proxmox host was pointed at 1.1.1.1 because the TP-Link DNS flaked. The UDM Pro is a real resolver, so 192.168.0.1 is safe again as secondary. Leave 1.1.1.1 primary." }
];

export const NOTE_HTML = "<b>Skip IPS on day one.</b> UDM Pro threat management caps routing around 3.5 Gbps and adds latency to the WireGuard tunnel. Get the rack stable, then enable it. At a 1 Gbps WAN it will not be the limiter either way.";
export const FOOTER = "Server facts (RTL8126 5GbE at 1000 Mb/s, 11 running guests, static addressing) were read live from the Proxmox host. The UCI, UDM Pro and switch are Ubiquiti's own 3D models from store.ui.com; the PDUMH20 and SilverStone fronts are reconstructed from product references. Cabinet details and PC rear port locations are schematic; the PDU meter is illustrative, not live telemetry. Etherlighting colors follow this page's speed legend; set the switch to color by speed to match. ISP tier and current upload/download throughput are unverified; the speed view shows planned link ceilings, not live traffic. Gaming PC and Sam's PC assumed to have 2.5 GbE onboard; if either is 1 GbE it links at 1 GbE on the same port with nothing else to change.";
